theme: jekyll-theme-minimal
title: ESSLLI 2024 Course on Large Language Models, Knowledge, and Reasoning - Generative AI and Symbolic Knowledge Representations
logo: /assets/img/logo-iu-red.png
description: This is the repo of the ESSLLI 2024 course on Large Language Models, Knowledge, and Reasoning.
show_downloads: false
